name: Davin Bujalski
favicon: null
layout_spectrum: 0.5224015146959573
typography_spectrum: 0.02888139500282705
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6631464066449553
  lightness: 0.2727371610235423
  saturation: 0.6052246412727982
  rhythmicContrast: 0.27473968314006925
purpose: []
